### ISSUE TITLE
Luigis showing invalid syntax ?

### ISSUE THREAD

**Issue by pinninti19** [samuell/luigis_monkey_wrench#2]
HI
I try to run it showing invalid syntax, Can you help me in building my own pipeline for genome analysis ?
****
Curium:~/test1mw/luigis_monkey_wrench$  python workflow_example.py --local-scheduler MyWorkFlow
Traceback (most recent call last):
  File "workflow_example.py", line 2, in <module>
    from luigis_monkey_wrench import *
  File "/home/likithreddy/test1mw/luigis_monkey_wrench/luigis_monkey_wrench/__init__.py", line 86
    print commands.getstatusoutput(cmd)
                 ^
SyntaxError: invalid syntax

**Comment by samuell** [comment]
Hi @pinninti19 note that this library is no longer maintained (I put up a more visible notice on the README.md file now, that it is deprecated).

Unfortunately I don't have time to support this library, or to provide general bioinformatics help.

If you need a lot of support, you might want to consider using a more established pipeline tool like [Nextflow](http://nextflow.io) or [Snakemake](http://snakemake.readthedocs.io), which has pretty large communities already, that can help out.

Also, for general bioinformatics support, in case you haven't checked out them yet, have a look at the following community driven support sites:

- [BioStars](http://biostars.org/)
- [Bioinformatics StackExchange](https://bioinformatics.stackexchange.com/)

Kind Regards
// Samuel
